name: Build & Package

on: push
  
jobs:
    build:
      runs-on: macos-latest
  
      steps:
        - name: Clone
          uses: actions/checkout@v2
        - name: Install jsoncpp
          run: |
            export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
            brew install jsoncpp
        - name: Build
          run: |
            make DESTDIR=$PWD/DSTROOT install
        - name: Package
          run: |
            cd $PWD/DSTROOT
            tar -cvf EmbeddedDeviceMap-1.tar.xz .
        - name: Upload
          if: success()
          uses: actions/upload-artifact@v4
          with:
            name: EmbeddedDeviceMap-1.tar.xz
            path: DSTROOT/EmbeddedDeviceMap-1.tar.xz
