name: Build & Package

on: push
  
jobs:
    build:
      runs-on: macos-latest
  
      steps:
        - name: Clone
          uses: actions/checkout@v2
        - name: Install Embedded Device Map
          run: |
            make DESTDIR=$PWD/DSTROOT install
        - name: Package Kernel into tarball
          run: |
            cd $PWD/DSTROOT
            tar -cvf EmbeddedDeviceMap-1.tar.xz .
        - name: Upload Kernel Root tarball
          if: success()
          uses: actions/upload-artifact@v4
          with:
            name: EmbeddedDeviceMap-1.tar.xz
            path: DSTROOT/EmbeddedDeviceMap-1.tar.xz
